classDiagram
    class Recettes {
        +int id_recette
        +String titre
        +String ingredients
        +String consignes
        +float note
        +String categorie
        +String origine
        +String commentaire
        +ajouter()
        +afficher_une_recette()
    }

    class Ingredients {
        +int id_ingredient
        +String nom
        +float quantite
        +afficher()
        +ajouter_ingredients()
    }

    class Utilisateur {
        +int id_utilisateur
        +String pseudo
        +String mot_de_passe
        +se_connecter()
        +creer_un_compte()
        +supprimer()
        +pseudo_deja_utilise()
        +modifier()
    }

    class Liste_de_courses {
        +int id_utilisateur
        +string elements
        +ajouter_ingredients()
        +afficher()
        +supprimer()
    }

    class Recettes_favorites {
        +int id_utilisateur
        +ajouter()
        +supprimer()
        +afficher()
    }

    class Avis {
        +int id_utilisateur
        +int recette
    }

    class Ingredients_favoris {
        +int id_utilisateur
    }

    class Ingredients_non_desires {
        +int id_utilisateur
    }

    class Regime_alimentaire {
        +int id_regime_alimentaire
    }

    class Recette_DAO {
        +ajouter_recette()
        +obtenir_recette_par_id()
        +fermer_connexion()
    }

    class Recette_Service {
        +ajouter_nouvelle_recette()
        +afficher_recette()
    }
    class Utilisateur_Service {

    }

    %% Relations d'héritage
    Recettes_favorites --|> Recettes : hérite de
    Ingredients_favoris --|> Ingredients : hérite de
    Ingredients_non_desires --|> Ingredients : hérite de
    Utilisateur_Service --|> Utilisateur

    %% Relations DAO et Service
    Recette_Service --> RecetteDAO : utilise
    Recette_DAO --> Recettes : gère

    %% Relations diverses avec cardinalités
    Utilisateur "1..*" --> "0..*" Recettes_favorites : possède
    Utilisateur "1" --> "0..*" Avis : donne des avis
    Utilisateur "1..*" --> "0..*" Ingredients_favoris : possède
    Utilisateur "1..*" --> "0..*" Ingredients_non_desires : ne consomme pas
    Recettes "1" --> "0..*" Avis : reçoit
    Recettes "1..*" --> "1..*" Ingredients : contient
     %% Relations de composition
     Liste_de_courses *-- Ingredients : contient


