classDiagram
    class Recettes {
        +int id_recette
        +String titre
        +String ingredients
        +String consignes
        +float note
        +String categorie
        +String origine
        +String commentaire
        +ajouter()
        +afficher_une_recette() : str
    }

    class Ingredients {
        +int id_ingredient
        +String nom
        +float quantite
        +afficher() : str
        +ajouter_ingredients()
    }

    class Utilisateur {
        +int id_utilisateur
        +String pseudo
        +String mot_de_passe
        +se_connecter()
        +creer_un_compte()
        +supprimer() : bool
        +pseudo_deja_utilise() : bool
        +modifier() : bool
    }

    class Liste_de_courses {
        +int id_utilisateur
        +string elements
        +ajouter_ingredients()
        +afficher() : list[ingredients]
        +supprimer_ingredient() : bool
    }

    class Recettes_favorites {
        +int id_utilisateur
        +ajouter() : bool
        +supprimer() : bool
        +afficher() : str
    }

    class Avis {
        +int id_utilisateur
        +int recette
    }

    class Ingredients_favoris {
        +int id_utilisateur
    }

    class Ingredients_non_desires {
        +int id_utilisateur
    }

    class Recette_DAO {
        +ajouter_recette()
        +obtenir_recette_par_id() :str
        +fermer_connexion()
    }

    class Recette_Service {
        +ajouter_nouvelle_recette()
        +afficher_recette() : str
    }
    class Utilisateur_Service {

    }
    class Utilisateur_DAO {

    }

    %% Relations d'héritage
    Recettes_favorites --|> Recettes : hérite de
    Ingredients_favoris --|> Ingredients : hérite de
    Ingredients_non_desires --|> Ingredients : hérite de

    %% Relations DAO et Service
    Recette_Service --> Recette_DAO : utilise
    Recette_DAO --> Recettes : gère
    Utilisateur_Service --> Utilisateur_DAO : utilise
    Utilisateur_DAO --> Utilisateur : gère

    %% Relations diverses avec cardinalités
    Utilisateur "1..*" --> "0..*" Recettes_favorites : possède
    Utilisateur "1" --> "0..*" Avis : donne des avis
    Utilisateur "1..*" --> "0..*" Ingredients_favoris : possède
    Utilisateur "1..*" --> "0..*" Ingredients_non_desires : ne consomme pas
    Recettes "1" --> "0..*" Avis : reçoit
     %% Relations de composition
     Liste_de_courses "1.."--* "1.." Ingredients : contient
     Recettes "1.."--* "1.." Ingredients : contient



