classDiagram
    class Recettes {
        +int idRecette
        +String titre
        +List<Ingredients> ingredients
        +String consignes
        +float note
        +String categorie
        +String origine
        +String commentaire
        +ajouter()
        +afficherUneRecette() : str
    }

    class Ingredients {
        +int idIngredient
        +String nom
        +float quantite
        +afficher() : str
        +ajouterIngredients()
    }

    class Utilisateur {
        +int idUtilisateur
        +String pseudo
        +String motDePasse
        +String adresseMail
    }

    class ListeDeCourses {
        +int idListe
        +List<Ingredients> ingredients
        +ajouterIngredients()
        +afficherListe() : list[Ingredients]
        +supprimerIngredient() : bool
    }

    class Avis {
        +int idAvis
        +int idUtilisateur
        +int idRecette
        +float note
        +String commentaire
    }

    %% DAO and Service classes

    class RecetteDAO {
        +ajouterRecette()
        +obtenirRecetteParId() : str
        +fermerConnexion()
    }

    class RecetteService {
        +ajouterNouvelleRecette()
        +afficherRecette() : str
    }

    class IngredientsDAO {
        +ajouterIngredient()
        +obtenirIngredientParId() : str
    }

    class IngredientsService {
        +ajouterNouvelIngredient()
    }

    class UtilisateurService {
        +seConnecter() : bool
        +creerUnCompte() : bool
        +supprimerCompte() : bool
        +pseudoDejaUtilise() : bool
    }

    class UtilisateurDAO {
        +ajouterUtilisateur()
        +obtenirUtilisateurParId() : Utilisateur
    }

    class ListeDeCoursesDAO {
        +ajouterListeDeCourses()
        +obtenirListeParId() : ListeDeCourses
    }

    class ListeDeCoursesService {
        +ajouterNouvelleListe()
    }

    class AvisDAO {
        +ajouterAvis()
        +obtenirAvisParId() : Avis
    }

    class AvisService {
        +ajouterNouvelAvis()
    }

    %% Relations
    RecetteService --> RecetteDAO : utilise
    RecetteDAO --> Recettes : gère

    IngredientsService --> IngredientsDAO : utilise
    IngredientsDAO --> Ingredients : gère

    UtilisateurService --> UtilisateurDAO : utilise
    UtilisateurDAO --> Utilisateur : gère

    ListeDeCoursesService --> ListeDeCoursesDAO : utilise
    ListeDeCoursesDAO --> ListeDeCourses : gère

    AvisService --> AvisDAO : utilise
    AvisDAO --> Avis : gère

    %% Cardinalities
    Utilisateur "1" --> "0..*" Recettes : crée
    Utilisateur "1" --> "0..*" Avis : donne des avis
    Utilisateur "1" --> "0..1" ListeDeCourses : possède
    Recettes "1.."--* "1.." Ingredients : contient
    ListeDeCourses "1.."--* "1.." Ingredients : contient
    Recettes "1" --> "0..*" Avis : reçoit


